volumes:
  postgres:
    driver: local
    name: postgres-data

networks:
  api-network:
    driver: bridge

services:
  postgresql:
    platform: linux/amd64
    image: postgres:17-alpine
    container_name: rekindle-db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGPORT=${DB_PORT}
    networks:
      - api-network
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
